apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: gitops
  namespace: my-app
spec:
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
  dex:
    openShiftOAuth: true
  image: 'registry.taco.moe/argo'
  rbac:
    policy: g, system:cluster-admins, role:admin
    scopes: '[groups]'
  repo:
    # NOTE: Even though it uses the same image, you must specify the image and
    # version for the repo server
    image: 'registry.taco.moe/argo'
    mountsatoken: true
    serviceaccount: gitops-argocd-server
    version: latest
  server:
    route:
      enabled: true
  version: latest
