apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: my-app
  namespace: vault-server
spec:
  authentication:
    path: admin
    role: admin
    serviceAccount:
      name: vault-server
  path: hub
  policies:
    - hub-ns-read
  targetServiceAccounts:
    - gitops-argocd-server
  targetNamespaces:
    targetNamespaces:
      - my-app
