apiVersion: redhatcop.redhat.io/v1alpha1
kind: AuthEngineMount
metadata:
  name: hub
  namespace: vault-server
spec:
  authentication:
    path: admin
    role: admin
    serviceAccount:
      name: vault-server
  type: kubernetes
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineConfig
metadata:
  name: hub
  namespace: vault-server
spec:
  authentication:
    path: admin
    role: admin
    serviceAccount:
      name: vault-server
  # NOTE: ISS validation isn't working; It must be disabled for
  # argocd-vault-plugin to work. Validation isn't working even if the
  # kubernetesHost value matches the "iis" value in the SA JWT.
  #
  # - Example -
  # kubernetesHost: https://kubernetes.default.svc
  # SA JWT has this: "iss":"https://kubernetes.default.svc"
  disableISSValidation: true
  tokenReviewerServiceAccount:
    name: vault-server
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: hub-ns-read
  namespace: vault-server
spec:
  authentication:
    path: admin
    role: admin
    serviceAccount:
      name: vault-server
  policy: |
    path "hub/data/my-app/*" {
       capabilities=["read","list"]
    }
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: hub
  namespace: vault-server
spec:
  authentication:
    path: admin
    role: admin
    serviceAccount:
      name: vault-server
  type: kv
  options:
    version: "2"
